theme: jekyll-theme-primer
title: Alzheimer's Disease Project
description: CS209A Final Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
